# Generated by Django 4.0 on 2021-12-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Date', models.DateField()),
                ('Weight', models.FloatField()),
                ('Rate', models.FloatField()),
                ('Description', models.TextField(max_length=100)),
            ],
        ),
    ]
