# Generated by Django 4.0 on 2021-12-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Contact',
            field=models.BigIntegerField(),
        ),
    ]
