# Generated by Django 4.0 on 2021-12-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Name',
            field=models.TextField(max_length=50),
        ),
    ]
