# Generated by Django 4.0 on 2021-12-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Due',
            field=models.IntegerField(default=0),
        ),
    ]
