# Generated by Django 4.0 on 2021-12-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_customer_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Date',
            field=models.TextField(max_length=50),
        ),
    ]
