# Generated by Django 4.0 on 2021-12-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Detail',
            field=models.TextField(default=' ', max_length=50),
        ),
    ]
