# Generated by Django 4.0 on 2021-12-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_detail_remove_customer_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='ID',
            field=models.TextField(default=0, max_length=50),
        ),
    ]
