# Generated by Django 4.0 on 2021-12-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_customer_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Detail',
            field=models.TextField(default=' ', max_length=50),
        ),
    ]
