# Generated by Django 4.0 on 2021-12-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customer_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Detail',
        ),
    ]
